### ISSUE TITLE
source for mini DIN connector

### ISSUE THREAD

**Issue by cogwheelcircuitworks** [BG6LH/FT-81x-BT-DIGI-Adaptor#2]
Can someone provide source for the mini DIN connectors..

Also, is there a chat group where people are sharing experience building this? Tnx.

**Comment by BG6LH** [comment]
The kind of connecter on the left pic is recommended.

![image](https://github.com/BG6LH/FT-81x-BT-DIGI-Adaptor/assets/527083/f1ed910c-124f-4bcf-9958-3cffe97e293c)

There is no group now.
Any question is welcome, please leave it here.

**Comment by erkanz** [comment]
Hello , Do you have the part number for the connectors? Where can I order it from? Thank you.

**Comment by BG6LH** [comment]
no part number could be found. it should be solved by yourself.
