### ISSUE TITLE
Sending AT commands

### ISSUE THREAD

**Issue by CT7ABA** [BG6LH/FT-81x-BT-DIGI-Adaptor#4]
Hello, I need your help for configuring the module.
I'm trying to connect to the module with an usb to serial adapter and a terminal program but it does not work.
Is there a pin to enable the module to receive AT commands?

I can change the frequency over bluetooth but i do not recive audio.
I'm using the FT8CN software.

mni tnx es 73 de Frederico

**Comment by BG6LH** [comment]
have you tried AT commands with or without the "\r\n"?

**Comment by CT7ABA** [comment]
It does not work with and without, it looks like I got some fake modules.
I have create my own PCB with the BT-401 Module and it works fine
73 Frederico.

**Comment by CT7ABA** [comment]
thanks

**Comment by BG6LH** [comment]
BT401 is my next target.
